### ISSUE TITLE
Introduce common formatting rules to minimise reformatting diffs in pull requests

### ISSUE THREAD

**Issue by tdziurko** [tdziurko/jvm-bloggers#112]

**Comment by delor** [comment]
Can we make sure that there is end-of-line at the end of each file?

**Comment by goostleek** [comment]
There is such option in [Eclipse formatter](http://snag.gy/zE8kM.jpg). I will include it in the formatter I'm just preparing. Let somebody take care of IntelliJ then.

**Comment by tdziurko** [comment]
First we should add it to the checkstyle :)

On 14 March 2016 at 12:01, Marcin Kłopotek <notifications@github.com> wrote:

> There is such option in Eclipse formatter <http://snag.gy/zE8kM.jpg>. I
> will include it in the formatter I'm just preparing. Let somebody take care
> of IntelliJ then.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tdziurko/jvm-bloggers/issues/112#issuecomment-196259900>
> .
>



-- 
Regards / Pozdrawiam,
Tomek Dziurko
http://tomaszdziurko.pl

**Comment by goostleek** [comment]
@tdziurko I'm wondering to keep just one formatter file. It can be error prone and painful having to formatters (Idea and Eclipse) to maintain. A change in one will require the same change in the other one and vice versa. There is a plugin for [importing Eclipse formatter settings into Idea](https://blog.jetbrains.com/idea/2014/01/intellij-idea-13-importing-code-formatter-settings-from-eclipse/) there is [no plugin to import it in an opposite direction](http://stackoverflow.com/questions/19791194/import-intellij-formatter-options-into-eclipse) so the choice is simple - keeping Eclipse formatter only.

**Comment by tdziurko** [comment]
I see that there are some issues with this plugin. We have a single source of truth in checkstyle. If many issues appear with two formatters I will vote for moving to Eclipse based one.

**Comment by goostleek** [comment]
Updated with #139

**Comment by goostleek** [comment]
Updated with #173
