### ISSUE TITLE
Design and introduce internal tagging system for github issues

### ISSUE THREAD

**Issue by cslysy** [tdziurko/jvm-bloggers#113]
In order to get our issues better organised some styleguide for tagging need to be introduced. See https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/ for inspirations.

**Comment by tdziurko** [comment]
Some tagging approach is ready for review :)

https://github.com/tdziurko/jvm-bloggers/labels

**Comment by delor** [comment]
:+1:

**Comment by cslysy** [comment]
:+1: W can always extend this list in the future.

**Comment by goostleek** [comment]
:+1:

**Comment by tdziurko** [comment]
Ok, so marking as done.
