### ISSUE TITLE
Show current page number in data table at moderation page

### ISSUE THREAD

**Issue by tdziurko** [tdziurko/jvm-bloggers#117]
Currently user does not know page number of paginated data at Moderation Page. It would be good to see page number and total number of records or even better (see current page number as non-clickable number in paginator)

Paginator view without visible page number and total records:
http://screencast.com/t/RjZJ8RQXSn5

**Comment by jborkowski** [comment]
Could I try implement this?

**Comment by goostleek** [comment]
Sure, make yourself at home :-)

**Comment by jborkowski** [comment]
Could I ask how should it look like? I prepared a proposal, but I do not know the expected appearance.

http://imgur.com/Btrzx0k

**Comment by tdziurko** [comment]
Looks great! :)

On 20 March 2016 at 09:37, Jonatan Borkowski <notifications@github.com>
wrote:

> Could I ask how should it look like? I prepared a proposal, but I do not
> know the expected appearance.
>
> http://imgur.com/Btrzx0k
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tdziurko/jvm-bloggers/issues/117#issuecomment-198872473>
>



-- 
Regards / Pozdrawiam,
Tomek Dziurko
http://tomaszdziurko.pl
