### ISSUE TITLE
Update Rome library to the latest version to avoid XML parsing DoS attack

### ISSUE THREAD

**Issue by goostleek** [tdziurko/jvm-bloggers#119]
Current [Rome](https://github.com/rometools/rome) RSS library version is very old and vulnerable to [Billion Laughs](https://www.wikiwand.com/en/Billion_laughs#/Details) XML parsing attack. It should be updated to the latest one ([1.5.1](http://mvnrepository.com/artifact/com.rometools/rome/1.5.1) at the time of writing this). Bumping the version is not enough, it will also require some refactoring due to package structure changes.

**Comment by puradawid** [comment]
I am working on it now. Let me know if you have any doubts about this :)

**Comment by goostleek** [comment]
Isn't it already done in PR:#140?

**Comment by puradawid** [comment]
Oh, right :) Thanks
