### ISSUE TITLE
Posts that will go in the next newsletter should be highlighted somehow at moderation page

### ISSUE THREAD

**Issue by tdziurko** [tdziurko/jvm-bloggers#121]
Currently it is hard to see which posts will go in next newsletter. We should modify rows with posts newer than "lastFriday-12:00" so it will be easy to spot.

**Comment by mszarlinski** [comment]
I can apply some kind of "greyed-out" style to rows for already published posts. I would like also to hide approve/reject buttons for those (I assume that I doesn't make sense to approve or reject posts from previous week). It should be sufficient as blog posts are sorted by "Date published", so the new ones are always on top of the list.

**Comment by tdziurko** [comment]
* Maybe bold (add star or something else with styling) to posts that will be included in a next newsletter?
* Hiding button - ok
* They are sorted by "Date published" but another issue #118 will order them by `"not moderated", date published desc`

**Comment by mszarlinski** [comment]
Good idea. I can deal with sorting as well, you can assign #118 to me.
