### ISSUE TITLE
New blogs in the newsletter should contain UTM parameters

### ISSUE THREAD

**Issue by tdziurko** [tdziurko/jvm-bloggers#122]
We already add UTM params to all links to new blog posts (see #100 ), but we also should add them to the links of newly added blogs.

**Comment by cslysy** [comment]
I will take care of this.

**Comment by goostleek** [comment]
@cslysy Please postponte till #56 is done. I almost finished it. I also did some refactoring there regarding _UTM _ params building. Now this is done not by `BlogPostForMailItem` but by external class which is responsible only for _UTM_ components creation.

**Comment by cslysy** [comment]
@goostleek As #56 is closed I start working on that.

**Comment by cslysy** [comment]
Hi @tdziurko,

Should we send newly added blog to the newsletter template when its url could not be reached during the last bloggers data refresh?

**Comment by cslysy** [comment]
I know, it was a question to Tomek :wink:  Nevertheless, blogs data (including blog url) are refreshed once a day. When last refresh before generating newsletter could not retrieve blog data and that blog was newly added it will not be attached into newsletter (blog entry remains in database and will be checked again during next day refresh). Sending blog url to newsletter template is independent from #66 which can be done simultaneously/later. What do you think?
