### ISSUE TITLE
Blog posts fetching frequency adjustment

### ISSUE THREAD

**Issue by goostleek** [tdziurko/jvm-bloggers#123]
I'm concerned about blog posts fetching frequency. IMHO the frequency is too high (every 10 minutes). I think once or twice a day will be enough.

Additionally we can introduce manual triggering form administration panel for some maintenance purposes.

What do you think?

**Comment by tdziurko** [comment]
I agree :) This was something I was thinking about some time ago but forgot when more important/exciting stuff came to my mind.

I would:
 - fetch new blogs two times a day (e.g. 9 am and 9 pm, generally any hour not clashing with 12 o;clock when mailing is sent)
 - fetch new blog posts every 6 hours
- allow to trigger both fetching manually from admin panel
 - store dates of last execution of each of fetching process and display then next to the buttons to trigger manual fetch.

WDYT?

**Comment by tdziurko** [comment]
Ok, closing this one and creating issues for these features.
