### ISSUE TITLE
Investigate and improve mail sending process to reduce chances of landing in Spam 

### ISSUE THREAD

**Issue by tdziurko** [tdziurko/jvm-bloggers#130]
Currently part of sent newsletter messages land in Spam folders in Google mailing groups. Thiis is a really major problem as group owners have to manuall approve such messages resulting in delayed delivery.

**Comment by tdziurko** [comment]
Major factors that probably contribute to newsletter being marked as a spam:

* many links, less text
* to send to google groups we must use gmail account, but Mailgun requires (or suggests) linking his account with som real domain (in our case it is jvm-bloggers.com)
* we send about 12-15 emails in a very short time (within a 1-2 minutes)

My ideas to improve/fix situation are:
1. Check if we could add description from the blog posts to the mailing newsletter to improve text/link ratio
2. Stop using Mailgun and send directly from gmail account using SMPT
3. Throttle sending with randomised delays (3-5 minutes between each sent message)
4. Check for suggestions from https://groups.google.com/forum/?fromgroups#!topic/warszawa-jug/cQzx1CDkBpQ

Any ideas/suggestions are more than needed :)

**Comment by adamdec** [comment]
Only gmail classifies our mailing as a spam or also others?
Btw...there is a typo in 2. SMPT :p

**Comment by tdziurko** [comment]
We are sending newsletter to all jugs in Poland to their mailing lists:
12 or 15 email addresses like `miasto-jug@googlegroups.com`

**Comment by goostleek** [comment]
In f8fad29 you provided a solution which is not advised in _Akka_ (see [this](http://stackoverflow.com/a/25790049/2443502) for details).

**Comment by tdziurko** [comment]
But sending is not using Akka

-- 
Tomasz Dziurko
Sent from my Nokia 3310
18 mar 2016 06:28 "Marcin Kłopotek" <notifications@github.com> napisał(a):

**Comment by goostleek** [comment]
[This change](https://github.com/tdziurko/jvm-bloggers/commit/f8fad2931c094ba8260c48271269f90bf69744aa#diff-0a8d53ebf3df219ab79d078c4a2ca475R72) causes unit tests execution time to increase to 5 minutes.

**Comment by goostleek** [comment]
@delor proposed to have distinct sleep values for deafult and test profiles.

**Comment by delor** [comment]
@goostleek you must have misunderstood me. What I had in mind was exactly the same as your proposition.

**Comment by tdziurko** [comment]
So far we have improved what can be improved. Still there is a problem with too many links in our mails :)
