### ISSUE TITLE
Fail fast on invalid entity instead of persit time SQLException

### ISSUE THREAD

**Issue by goostleek** [tdziurko/jvm-bloggers#147]
We can add [`@NonNull`](https://projectlombok.org/features/NonNull.html) annotation on non nullable fields in our entities (in [`Blog`](https://github.com/tdziurko/jvm-bloggers/blob/master/src/main/java/pl/tomaszdziurko/jvm_bloggers/blogs/domain/Blog.java#L33) entity for example) to avoid `SQLException` at persist time when particular non nullable field on given entity is not set (`null`). `@NonNull` annotation will raise NPE faster so we can just fail on entity creation (before entity is saved). This will make tracing errors much easier than digging through stack traces of `SQLException`. WDYT?

**Comment by cslysy** [comment]
Fail-fast is always welcome for me :+1:

**Comment by adamdec** [comment]
Sounds good. @NonNull from Lombok of course?

**Comment by tdziurko** [comment]
Any update on this? :) @goostleek

**Comment by goostleek** [comment]
I think we can proceed with that one. The discussion is over. There were no objections to the proposed approach.
