### ISSUE TITLE
Microservices architecture? :)

### ISSUE THREAD

**Issue by tdziurko** [tdziurko/jvm-bloggers#151]
Once we have website there are some additional features to be implemented:
* posting newsletter issue at FaceBook fan page
* posting info about newsletter on Twitter with link
* gathering data about most commented blog posts (parsing comments from each blog post)
* gathering data about most popular tweets (RT, likes) and conversations from people on the list

And each of these feature can be implemented using two completely different approaches:
a) as a modules in the existing application
b) as a separate microservice deployed next to existing application and communicating via either REST or even some message bus (Kafka or something  similar)

What are you thoughts about each of these approaches? :)

**Comment by cslysy** [comment]
> gathering data about most commented blog posts

This will be very tricky to implement because people may use blog built-in or external (disqus/facebook/...) comments provider

**Comment by tdziurko** [comment]
What I see as a disadvantages of microservice architecture approach:
* we need many repositories so migration to GitHub organisation will be required
* many repositories mean many lists of issues/PR-s etc so it will be very difficult to manage all of this
* no single place with "to-do list"
* much harder for the newcomers to get an idea how this project is actually working
* if we allow different languages, we will go through pain of "agree on conventions" again

**Comment by goostleek** [comment]
I agree with all the points stated above. It may be tempting to do it with buzzed _microservices_ way but we will have no real gain doing it this way. Not to mention deployment problems related to microservices architecture. I'm thinking rather to split the features into separate parts and implement them as submodules which became dependencies for the main app.

**Comment by tdziurko** [comment]
I am more concerned about organisational issues than technical ones. Technical ones can be fixed easily :)
I've found one interesting sentence in ZenHub:

> Connect multiple repositories in one Task Board – and watch as your issues drag-and-drop to the Closed pipeline!

**Comment by puradawid** [comment]
There is no need to create separated (different repositories) projects now. I vote nay for this approach, because those services can be done as submodules without unnecessary overhead.

**Comment by delor** [comment]
I don't see how project would gain anything from moving towards microservices architecture other than really great exercise for developers. ;)

**Comment by tdziurko** [comment]
I see microservice architecture as a good opportunity to:

* try different languages and frameworks like Scala, Groovy, Ratback or maybe something not from JVM for a small module
* play with more sophisticated deployment using Docker and AWS 
* try Eureka or another Service Discovery tool
* experiment with event based communication like Kafka or something similar :)
