### ISSUE TITLE
Limit number of entries in rss to 100

### ISSUE THREAD

**Issue by tdziurko** [tdziurko/jvm-bloggers#154]
We do not have to put all blog posts into generated rss. Standard approach is to put last 10 items, but we can easily put latest 25 blog posts there.

**Comment by tdziurko** [comment]
We have decided to wait with any changes to RSS for a feedback from users. Maybe large number of entries won't be a problem.

**Comment by tdziurko** [comment]
Ok, there is first complain: one user said that his RSS Firefox reader hangs on our RSS :) Maybe we could cut this number a bit? To 100 for a start maybe? :)

**Comment by goostleek** [comment]
Seems ok. I will handle it tomorrow.

**Comment by zsokolowski** [comment]
H Guys!

Nice project, unfortunately user using live bookmarks in Firefox don't have a possibility change url, I don't know if you clip value of url to 100 or not. But it still doesn't work. Please see at attached screenshots. Please add reasonable default value let say 50 or even better 25. This is the only rss from approximately 50 which freezes my FF. Thanks! 

![jvmbloggers2](https://cloud.githubusercontent.com/assets/4411391/14406011/b46da61e-fe9c-11e5-9b09-3be5bf10f0cf.jpg)
![jvmbloggers1](https://cloud.githubusercontent.com/assets/4411391/14406013/b5de4a62-fe9c-11e5-94a5-84ede0e3bb7e.jpg)

**Comment by goostleek** [comment]
It's been already implemented but not yet deployed to production. The RSS is limited to 100 items by default but the value can be overriden by appending `limit` query parameter with desired number of the most recent posts to the RSS url: `http://jvm-bloggers.com/pl/rss? limit=25`.

**Comment by zsokolowski** [comment]
Why 100, isn't too much? 50 it should be too much to scroll down, query there is no option to override it in FF.
