### ISSUE TITLE
Create rest endpoint redirecting to given blog post basing on uid

### ISSUE THREAD

**Issue by tdziurko** [tdziurko/jvm-bloggers#228]
it should be something like *http://jvm-bloggers/com/r/aqw234rtf*

**Comment by matek2305** [comment]
Hey, I have some free time now and I would like to work on it

**Comment by tdziurko** [comment]
Ok, so requirements are as follows:
1. It should be fast :)


Things to keep in mind:
1. Later on we will add there a feature to store those redirections in database to track number of clicks.

**Comment by matek2305** [comment]
Sure, I try my best :) I understand that for now I can do this using uid we have now which are pretty long? Also, should I add UTM parameters to each redirect destination? f.e. should http://jvm-bloggers.com/r/aqw234rtf redirect to http://some.blog.com/blogpost or http://some.blog.com/blogpost?utm_paramsblabla ?

**Comment by tdziurko** [comment]
1. http://jvm-bloggers.com/r/aqw234rtf is enough
2. Please use uid, I am im the middle of converting it to something shorter (field name and type won't change).

**Comment by matek2305** [comment]
Ok but are you sure that utm parameters is not needed? We had these parameters in newsletter, shouldn't it be replaced with redirect urls that automatically will add those params?

**Comment by tdziurko** [comment]
Hmm.. ok, let's keep those parameters as well.

**Comment by tdziurko** [comment]
Implemented in #232
