### ISSUE TITLE
Question: How can I view the newest articles?

### ISSUE THREAD

**Issue by pwittchen** [tdziurko/jvm-bloggers#46]
Hi,

Cool project! I have a question: How can I view the newest articles? I've found an information that it's deployed on your server. Can I subscribe for the newsletter with the newest blog articles or can I browse summary of the blog articles on a specific website?  It may be trivial question, but I haven't dived in this project and haven't found such information in `README.md`. :-)

Regards,
Piotr

**Comment by tdziurko** [comment]
Hello

As usual, the most obvious things were not included in the readme :) 

Currently I am sending a newsletter every Friday with new posts from last 7 days. There is no way to check all new posts at any time. Newsletter is sent to some JUG mailing lists across the Poland. If you want to read it, I can add your e-mail to the readers table in database or you can join/read e.g. Warsaw JUG mailing list.

**Comment by pwittchen** [comment]
Thanks. I joined https://groups.google.com/forum/#!forum/warszawa-jug and https://groups.google.com/forum/#!forum/polish-java-user-group group some time ago, but I haven't set e-mail subscription, because I didn't want to receive information about all of the posts from these groups. Nevertheless, now I know how to find the thing I was searching for. :-)
