### ISSUE TITLE
Add rss of all rss-es so people could subscribe to it directly

### ISSUE THREAD

**Issue by tdziurko** [tdziurko/jvm-bloggers#56]
**Requires #106**

**Comment by tdziurko** [comment]
Do you have any rough plan how to implement it? Can we clarify requirements before actual coding? :)

**Comment by tdziurko** [comment]
I want to talk mostly about functional requirements, not about implementation :) But the more cool technologies the better :)

**Comment by goostleek** [comment]
I always have a plan before I begin implementation :)

Let me elaborate then. 

1. First we need to iterate over all approved [`BlogPosts`](https://github.com/goostleek/jvm-bloggers/blob/issue/%23106/blog-post-description/src/main/java/pl/tomaszdziurko/jvm_bloggers/blog_posts/domain/BlogPost.java) and map it to [`SyndEntries`](http://javadox.com/rome/rome/1.0/com/sun/syndication/feed/synd/SyndEntry.html):
 * adding `findByApprovedTrue()` to [`BlogPostRepository`](https://github.com/goostleek/jvm-bloggers/blob/issue/%23106/blog-post-description/src/main/java/pl/tomaszdziurko/jvm_bloggers/blog_posts/domain/BlogPostRepository.java) will help with that
 * `BlogPostsToRssFeedProducer` service will do the mapping

2. Then create a controller and mount it at '/rss' path
 * it will invoke the newly created `BlogPostsToRssFeedProducer` service to return the [`SyndFeed`](http://javadox.com/rome/rome/1.0/com/sun/syndication/feed/synd/SyndFeed.html)
 * once the feed is created it's cached till BlogPostsFetchingScheduler is trigerred
 * [_Spring Cache Abstraction_](https://docs.spring.io/spring/docs/current/spring-framework-reference/html/cache.html) with [_Guava Cache_](http://docs.guava-libraries.googlecode.com/git/javadoc/index.html?com/google/common/cache/Cache.html) as cache implementation provider will be used to cache generated feed.

**Comment by tdziurko** [comment]
1. Can we have `/pl/rss` path as an feed entry point? Maybe we will have another country in the project :)

2. What about ordering? We might have items A, B, D in rss feed and then admin approves item C and rss ordering changes to: A, B, C, D. Any ideas whether rss format allows adding in not only to the top of the queue or it does not care? :)

**Comment by tdziurko** [comment]
3. Can we in any way gather statistics about number of subscribers or any other stats?

**Comment by goostleek** [comment]
I have almost finished the implementation and I can say that:

1. Yes, currently _RSS_ feed is mounted at `/rss`. I will change it to `/pl/rss`.

2. Current implementation behaves exactly in the way you described. When administrator approves the post it will appear in _RSS_ feed in the appropriate position in the feed (items are sorted by published date - the most recent one will appear on top).

3. This is IMHO a topic for a separate issue. At the beginning we can just use http://jvm-bloggers.com/metrics endpoint for basic stats and add custom keys there later.
