### ISSUE TITLE
Dashboard: add counter for new posts since last mailing

### ISSUE THREAD

**Issue by tdziurko** [tdziurko/jvm-bloggers#77]
Replace example counters with a real logic and real values.

UI view: http://screencast.com/t/EC8nVxX9ay

**Comment by matek2305** [comment]
Hi, I can work on it if you dont mind

**Comment by tdziurko** [comment]
:+1:

**Comment by tdziurko** [comment]
If you need any help with Apache Wicket, please let me know :)

**Comment by matek2305** [comment]
Sure, I just created pull request for it but that was my first experience with Apache wicket so I don't know if I have done it right way
