### ISSUE TITLE
Links to the blog posts should go through our application so we could count clicks.

### ISSUE THREAD

**Issue by tdziurko** [tdziurko/jvm-bloggers#8]

**Comment by kubamarchwicki** [comment]
Tomku, bardzo fajna inicjatywa - widać ja _traffic_ rośnie po każdym poście. Mam w związku z tym wniosek racjonalizatorski, poniekąd związany z Click counterem.

Jeżeli linki będą szły przez jvmbloggers aby zliczyć kliknięcia to po stronie - to w Google Analytics zacznie pojawiać się referal, co może być ciekawą informację. Ale może - nim to zostanie zaimplementowane to jakiś krok pośredni [UTM parameters](https://blog.kissmetrics.com/social-media-utm-parameters/)
Jeżeli do URLa dodałbyś 3 atrybuty to każdy mógłby zobaczyć jak wiele ruchu przychodzi na danego bloga po Twoim mailingu. Dla przykładu
http://{link}?utm_source=jvmbloggers&utm_medium=link&utm_campaign=jvmblogers#21

**Comment by tdziurko** [comment]
Hej. Dzięki za pomysł, wygląda na prosty do zrobienia i bardzo mało inwazyjny. Obadam to :)
