### ISSUE TITLE
Add UTM parameters to the links in the newsletter

### ISSUE THREAD

**Issue by tdziurko** [tdziurko/jvm-bloggers#90]
This is idea suggested in https://github.com/tdziurko/jvm-bloggers/issues/8

Simply goal is to add [UTM parameters](https://blog.kissmetrics.com/social-media-utm-parameters/) to each link incluved in the newsletter.

Something like:
http://{link}?utm_source=jvmbloggers&utm_medium=newsletter&utm_campaign=jvmblogers#21

**Comment by cslysy** [comment]
Hi Tomasz,

May I join the project? Is someone working on this task currently?

**Comment by tdziurko** [comment]
Sure, please join. No one as far as I know :) Write a comment saying that you are working on selected feature (this one for example) so no one starts coding same stuff :)

And join Gitter :)

**Comment by cslysy** [comment]
Thanks :) I'm on it!

**Comment by cslysy** [comment]
There are no source from utm_campaign identifier could be build from.  According to the wikipedia campaign date can be used for this purpose:

> utm_campaign = name of the campaign, f.e. name of the campaign in Google AdWords, date of your e-mail campaign, etc.

Is it ok for you to build utm_campaign like `utm_campaign=jvmblogers#2015-02-02` where 2015-02-02 is a date of sending newsletter?

**Comment by cslysy** [comment]
Pull request #100 submitted, waiting for code review.
