### ISSUE TITLE
Migrate to a smaller linux distro to reduce docker image size

### ISSUE THREAD

**Issue by tdziurko** [tdziurko/jvm-bloggers#91]
Consider https://github.com/iron-io/dockers/tree/master/java/java-1.8 or something similar as suggested in the comments to http://tomaszdziurko.pl/2016/01/dockerizing-spring-boot-application/

**Comment by krasinski** [comment]
#96

**Comment by tdziurko** [comment]
From 400MB to 200MB :)
https://hub.docker.com/r/tdziurko/jvm-bloggers/tags/

**Comment by krasinski** [comment]
Looks good :)
