### ISSUE TITLE
Mail administrator when brute force attacks occur

### ISSUE THREAD

**Issue by tdziurko** [tdziurko/jvm-bloggers#95]
When we start rejecting login attempts from given IP, please send e-mail to administrator

**Comment by adamdec** [comment]
I can work on it if you do not mind....

**Comment by tdziurko** [comment]
:+1:

**Comment by adamdec** [comment]
Please review PR, thank you

**Comment by adamdec** [comment]
Additionaly, I need to know:
- what is the admin e-mail?
- title and email content template are correct
